### ISSUE TITLE
Convert American Standard Version (ASV) Bible to JSON format

### ISSUE THREAD

**Issue by rkazakov** [rkazakov/usfm2json#1]
Convert American Standard Version (ASV) Bible to JSON format.
ASV USFM can be obtained from Unbound Bible website: 
https://unbound.biola.edu/index.cfm?method=downloads.showDownloadMain.

**Comment by sharton** [comment]
#3

**Comment by sharton** [comment]
https://github.com/dev4christ/usfm2json/pull/3/commits/9211a05e9a4d778cd1b1f4f4dcd74d89bb80690e
